module.exports.initializeEuropeanCountries = function(countries) {
    countries.push(
        {name: "Turkey", climate: "Warm", continent: "Europe", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Belgium", climate: "Cold", continent: "Europe", geo: "City", mood: "Relax", tours: "Museum"},
        {name: "Italy", climate: "Warm", continent: "Europe", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Spain", climate: "Warm", continent: "Europe", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Portugal", climate: "Warm", continent: "Europe", geo: "City", mood: "Relax", tours: "Food"},
        {name: "France", climate: "Warm", continent: "Europe", geo: "City", mood: "Relax", tours: "Museum"},
        {name: "The Netherlands", climate: "Cold", continent: "Europe", geo: "City", mood: "Relax", tours: "Museum"},
        {name: "United Kingdom", climate: "Cold", continent: "Europe", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Ireland", climate: "Cold", continent: "Europe", geo: "Nature", mood: "Experience", tours: "Museum"},
        {name: "Germany", climate: "Cold", continent: "Europe", geo: "City", mood: "Relax", tours: "Museum"},
        {name: "Russia", climate: "Cold", continent: "Europe", geo: "City", mood: "Experience", tours: "Food"},
        {name: "Ukraine", climate: "Cold", continent: "Europe", geo: "City", mood: "Experience", tours: "Food"},
        {name: "Sweden", climate: "Cold", continent: "Europe", geo: "Nature", mood: "Experience", tours: "Museum"},
        {name: "Norway", climate: "Cold", continent: "Europe", geo: "Nature", mood: "Experience", tours: "Museum"},
        {name: "Finland", climate: "Cold", continent: "Europe", geo: "Nature", mood: "Experience", tours: "Museum"},
        {name: "Poland", climate: "Cold", continent: "Europe", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Romania", climate: "Cold", continent: "Europe", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Belarus", climate: "Cold", continent: "Europe", geo: "City", mood: "Experience", tours: "Food"},
        {name: "Greece", climate: "Warm", continent: "Europe", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Bulgaria", climate: "Warm", continent: "Europe", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Iceland", climate: "Cold", continent: "Europe", geo: "Nature", mood: "Experience", tours: "Museum"},
        {name: "Hungary", climate: "Warm", continent: "Europe", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Austria", climate: "Cold", continent: "Europe", geo: "City", mood: "Relax", tours: "Museum"},
        {name: "Czech Republic", climate: "Cold", continent: "Europe", geo: "City", mood: "Relax", tours: "Museum"},
        {name: "Serbia", climate: "Warm", continent: "Europe", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Lithuania", climate: "Cold", continent: "Europe", geo: "City", mood: "Relax", tours: "Museum"},
        {name: "Latvia", climate: "Cold", continent: "Europe", geo: "City", mood: "Relax", tours: "Museum"},
        {name: "Croatia", climate: "Warm", continent: "Europe", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Bosnia And Herzegovina", climate: "Warm", continent: "Europe", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Slovakia", climate: "Cold", continent: "Europe", geo: "City", mood: "Relax", tours: "Museum"},
        {name: "Denmark", climate: "Cold", continent: "Europe", geo: "Nature", mood: "Relax", tours: "Museum"},
        {name: "Switzerland", climate: "Cold", continent: "Europe", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Moldova", climate: "Cold", continent: "Europe", geo: "City", mood: "Relax", tours: "Museum"},
        {name: "Albania", climate: "Warm", continent: "Europe", geo: "City", mood: "Relax", tours: "Food"},
        {name: "North Macedonia", climate: "Warm", continent: "Europe", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Slovenia", climate: "Cold", continent: "Europe", geo: "City", mood: "Relax", tours: "Museum"},
        {name: "Montenegro", climate: "Warm", continent: "Europe", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Kosovo", climate: "Warm", continent: "Europe", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Luxembourg", climate: "Cold", continent: "Europe", geo: "City", mood: "Relax", tours: "Museum"},
        {name: "Andorra", climate: "Warm", continent: "Europe", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Malta", climate: "Warm", continent: "Europe", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Liechtenstein", climate: "Cold", continent: "Europe", geo: "City", mood: "Relax", tours: "Museum"},
        {name: "San Marino", climate: "Warm", continent: "Europe", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Monaco", climate: "Warm", continent: "Europe", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Vatican City", climate: "Warm", continent: "Europe", geo: "City", mood: "Relax", tours: "Museum"},
        {name: "Cyprus", climate: "Warm", continent: "Asia", geo: "Nature", mood: "Experience", tours: "Food"}
    );
}

module.exports.initializeAsianCountries = function(countries) {
    countries.push(
        {name: "China", climate: "Warm", continent: "Asia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "India", climate: "Warm", continent: "Asia", geo: "City", mood: "Experience", tours: "Food"},
        {name: "Kazakhstan", climate: "Cold", continent: "Asia", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Saudi Arabia", climate: "Warm", continent: "Asia", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Iran", climate: "Warm", continent: "Asia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Mongolia", climate: "Cold", continent: "Asia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Indonesia", climate: "Warm", continent: "Asia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Pakistan", climate: "Warm", continent: "Asia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Myanmar", climate: "Warm", continent: "Asia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Afghanistan", climate: "Warm", continent: "Asia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Yemen", climate: "Warm", continent: "Asia", geo: "City", mood: "Experience", tours: "Food"},
        {name: "Thailand", climate: "Warm", continent: "Asia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Turkmenistan", climate: "Cold", continent: "Asia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Uzbekistan", climate: "Cold", continent: "Asia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Iraq", climate: "Warm", continent: "Asia", geo: "City", mood: "Experience", tours: "Food"},
        {name: "Japan", climate: "Cold", continent: "Asia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Bangladesh", climate: "Warm", continent: "Asia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Philippines", climate: "Warm", continent: "Asia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Vietnam", climate: "Warm", continent: "Asia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Turkey", climate: "Warm", continent: "Asia", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Malaysia", climate: "Warm", continent: "Asia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Nepal", climate: "Warm", continent: "Asia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "North Korea", climate: "Cold", continent: "Asia", geo: "City", mood: "Experience", tours: "Museum"},
        {name: "Sri Lanka", climate: "Warm", continent: "Asia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Syria", climate: "Warm", continent: "Asia", geo: "City", mood: "Experience", tours: "Food"},
        {name: "Cambodia", climate: "Warm", continent: "Asia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Jordan", climate: "Warm", continent: "Asia", geo: "City", mood: "Experience", tours: "Food"},
        {name: "Azerbaijan", climate: "Warm", continent: "Asia", geo: "City", mood: "Experience", tours: "Food"},
        {name: "United Arab Emirates", climate: "Warm", continent: "Asia", geo: "City", mood: "Experience", tours: "Food"},
        {name: "Tajikistan", climate: "Warm", continent: "Asia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Laos", climate: "Warm", continent: "Asia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Kyrgyzstan", climate: "Cold", continent: "Asia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Turkmenistan", climate: "Warm", continent: "Asia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Singapore", climate: "Warm", continent: "Asia", geo: "City", mood: "Relax", tours: "Museum"},
        {name: "Oman", climate: "Warm", continent: "Asia", geo: "City", mood: "Experience", tours: "Food"},
        {name: "Palestine", climate: "Warm", continent: "Asia", geo: "City", mood: "Experience", tours: "Food"},
        {name: "Kuwait", climate: "Warm", continent: "Asia", geo: "City", mood: "Experience", tours: "Food"},
        {name: "Georgia", climate: "Warm", continent: "Asia", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Mongolia", climate: "Cold", continent: "Asia", geo: "Nature", mood: "Relax", tours: "Museum"},
        {name: "Qatar", climate: "Warm", continent: "Asia", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Bahrain", climate: "Warm", continent: "Asia", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Cyprus", climate: "Warm", continent: "Asia", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Buthan", climate: "Warm", continent: "Asia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Maldives", climate: "Warm", continent: "Asia", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Brunei", climate: "Warm", continent: "Asia", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Taiwan", climate: "Warm", continent: "Asia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Hong Kong", climate: "Warm", continent: "Asia", geo: "City", mood: "Experience", tours: "Museum"}
    );
}

module.exports.initializeAfricanCountries = function(countries) {
    countries.push(
        {name: "Nigeria", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Ethiopia", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Egypt", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Congo", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Tanzania", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "South Africa", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Kenya", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Uganda", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Algeria", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Sudan", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Morocco", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Angola", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Mozambique", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Ghana", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Madagascar", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Cameroon", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Côte d'Ivore", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Niger", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Burkina Faso", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Mali", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Malawi", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Zambia", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Senegal", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Chad", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Somalia", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Zimbabwe", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Guinea", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Rwanda", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Benin", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Burundi", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Tunisia", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "South Sudan", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Togo", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Sierra Leone", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Libya", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Liberia", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Central African Republic", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Mauritania", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Eritrea", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Namibia", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Gambia", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Botswana", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Gabon", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Lesotho", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Guinea-Bissau", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Equatorial Guinea", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Mauritius", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Eswatini", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Djibouti", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Comoros", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Cabo Verde", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Seychelles", climate: "Warm", continent: "Africa", geo: "Nature", mood: "Relax", tours: "Food"}
    );
}